### PR TITLE
Update io_async.js

### PR DESCRIPTION
**Pull request by apricots**

### CODE REVIEW

**Comment by frasertweedale** [comment]
Hi @apricots, thanks for your pull request.  Could you please add spaces around the `-` operator, and I will promptly merge it.

**Comment by frasertweedale** [comment]
Superseded by #8.

**Comment by apricots** [comment]
Oh yay my first github interaction haha. Thanks!

**Comment by frasertweedale** [comment]
I hope it is the first of many :)

**Pull request closed without merging**
